#!/usr/bin/env python3
"""
OpenRCT2 Portable Suite Generator

Generates a complete OpenRCT2 portable USB suite with:
- Windows installer/updater BAT
- Windows dynamic USB VBS launcher with logging and log archive support
- Linux installer/updater SH
- macOS installer/updater SH
- launch helper scripts
- setup instructions

Run:
    python generate.py
"""

import zipfile
from pathlib import Path


class Generator:
    """
    Generates the OpenRCT2 portable setup guide folder and ZIP archive.
    """

    def __init__(
        self,
        package_dir: str = ".__OpenRCT2_Portable",
        zip_name: str = ".__OpenRCT2_Portable_SETUP.zip",
    ) -> None:
        self.package_dir = Path(package_dir)
        self.zip_name = zip_name
        self.setup_docs = {'Linux/99-openrct2.rules': 'ACTION=="add", SUBSYSTEM=="block", ENV{ID_FS_LABEL}=="OpenRCT2_USB", '
                            'RUN+="/usr/local/bin/usb_scanner.sh"\n',
 'Linux/SETUP_INSTRUCTIONS.txt': 'LINUX SETUP\n'
                                 '\n'
                                 'Files:\n'
                                 '- install_update_openrct2.sh\n'
                                 '- usb_scanner.sh\n'
                                 '- 99-openrct2.rules\n'
                                 '\n'
                                 'Manual install/update:\n'
                                 '1. Open terminal in the USB folder.\n'
                                 '2. Run:\n'
                                 '   chmod +x Linux/install_update_openrct2.sh\n'
                                 '   ./Linux/install_update_openrct2.sh\n'
                                 '\n'
                                 'The updater downloads:\n'
                                 'OpenRCT2-v*-linux-x86_64.AppImage\n'
                                 '\n'
                                 'Automatic launch note:\n'
                                 'udev is not reliable for launching GUI apps directly.\n'
                                 'The included udev rule is mainly a starting point/detection helper.\n'
                                 'A desktop autostart watcher is better for real daily use.\n',
 'Linux/install_update_openrct2.sh': '#!/usr/bin/env bash\n'
                                     'set -Eeuo pipefail\n'
                                     '\n'
                                     'SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"\n'
                                     'USB_ROOT="$SCRIPT_DIR"\n'
                                     '\n'
                                     'if [[ "$(basename "$SCRIPT_DIR")" == "Linux" ]]; then\n'
                                     '    USB_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"\n'
                                     'fi\n'
                                     '\n'
                                     'UPDATED_FILE="$USB_ROOT/updated-linux.txt"\n'
                                     'APPIMAGE_PATH="$USB_ROOT/OpenRCT2.AppImage"\n'
                                     'SYMLINK_PATH="$USB_ROOT/openrct2"\n'
                                     'DATA_DIR="$USB_ROOT/data"\n'
                                     'TEMP_DIR="$(mktemp -d)"\n'
                                     'RELEASE_INFO_FILE="$TEMP_DIR/release_info.txt"\n'
                                     'DOWNLOAD_FILE="$TEMP_DIR/OpenRCT2.AppImage"\n'
                                     'USER_AGENT="OpenRCT2PortableUpdater/1.0"\n'
                                     '\n'
                                     'cleanup() {\n'
                                     '    rm -rf "$TEMP_DIR"\n'
                                     '}\n'
                                     'trap cleanup EXIT\n'
                                     '\n'
                                     'echo "===================================================="\n'
                                     'echo "        OpenRCT2 Portable Auto-Updater - Linux"\n'
                                     'echo "===================================================="\n'
                                     'echo "Target directory: $USB_ROOT"\n'
                                     'echo\n'
                                     '\n'
                                     'echo "[1/5] Checking latest OpenRCT2 release from GitHub..."\n'
                                     '\n'
                                     'if ! command -v python3 >/dev/null 2>&1; then\n'
                                     '    echo "[ERROR] python3 is required for parsing the GitHub release JSON."\n'
                                     '    exit 1\n'
                                     'fi\n'
                                     '\n'
                                     'python3 - "$RELEASE_INFO_FILE" <<\'PY\'\n'
                                     'import json\n'
                                     'import sys\n'
                                     'import urllib.request\n'
                                     '\n'
                                     'output_file = sys.argv[1]\n'
                                     'url = "https://api.github.com/repos/OpenRCT2/OpenRCT2/releases/latest"\n'
                                     'request = urllib.request.Request(url, headers={"User-Agent": '
                                     '"OpenRCT2PortableUpdater/1.0"})\n'
                                     '\n'
                                     'with urllib.request.urlopen(request, timeout=60) as response:\n'
                                     '    release = json.loads(response.read().decode("utf-8"))\n'
                                     '\n'
                                     'tag = release.get("tag_name", "")\n'
                                     'asset = None\n'
                                     '\n'
                                     'for item in release.get("assets", []):\n'
                                     '    name = item.get("name", "")\n'
                                     '    if name.endswith("linux-x86_64.AppImage"):\n'
                                     '        asset = item\n'
                                     '        break\n'
                                     '\n'
                                     'if not tag or not asset:\n'
                                     '    raise SystemExit("Could not find latest linux-x86_64.AppImage asset.")\n'
                                     '\n'
                                     'with open(output_file, "w", encoding="utf-8") as f:\n'
                                     '    f.write(tag + "\\n")\n'
                                     '    f.write(asset["browser_download_url"] + "\\n")\n'
                                     '    f.write(asset["name"] + "\\n")\n'
                                     'PY\n'
                                     '\n'
                                     'LATEST_VERSION="$(sed -n \'1p\' "$RELEASE_INFO_FILE")"\n'
                                     'DOWNLOAD_URL="$(sed -n \'2p\' "$RELEASE_INFO_FILE")"\n'
                                     'ASSET_NAME="$(sed -n \'3p\' "$RELEASE_INFO_FILE")"\n'
                                     '\n'
                                     'if [[ -z "$LATEST_VERSION" || -z "$DOWNLOAD_URL" ]]; then\n'
                                     '    echo "[ERROR] Could not read GitHub release information."\n'
                                     '    exit 1\n'
                                     'fi\n'
                                     '\n'
                                     'echo "Latest version: $LATEST_VERSION"\n'
                                     'echo "Asset: $ASSET_NAME"\n'
                                     'echo\n'
                                     '\n'
                                     'echo "[2/5] Checking local installation..."\n'
                                     '\n'
                                     'NEEDS_UPDATE=0\n'
                                     'UPDATE_REASON=""\n'
                                     '\n'
                                     'if [[ ! -f "$APPIMAGE_PATH" ]]; then\n'
                                     '    NEEDS_UPDATE=1\n'
                                     '    UPDATE_REASON="OpenRCT2.AppImage is missing."\n'
                                     'elif [[ ! -f "$UPDATED_FILE" ]]; then\n'
                                     '    NEEDS_UPDATE=1\n'
                                     '    UPDATE_REASON="updated-linux.txt is missing."\n'
                                     'else\n'
                                     '    CURRENT_VERSION="$(head -n 1 "$UPDATED_FILE" || true)"\n'
                                     '    if [[ -z "$CURRENT_VERSION" ]]; then\n'
                                     '        NEEDS_UPDATE=1\n'
                                     '        UPDATE_REASON="updated-linux.txt is empty."\n'
                                     '    elif [[ "$CURRENT_VERSION" != "$LATEST_VERSION" ]]; then\n'
                                     '        NEEDS_UPDATE=1\n'
                                     '        UPDATE_REASON="Installed version \'$CURRENT_VERSION\' does not match '
                                     'latest \'$LATEST_VERSION\'."\n'
                                     '    fi\n'
                                     'fi\n'
                                     '\n'
                                     'if [[ "$NEEDS_UPDATE" == "0" ]]; then\n'
                                     '    echo "Current version: $(head -n 1 "$UPDATED_FILE")"\n'
                                     '    echo "Latest version:  $LATEST_VERSION"\n'
                                     '    echo\n'
                                     '    echo "===================================================="\n'
                                     '    echo " No new updates were found."\n'
                                     '    echo "===================================================="\n'
                                     '    exit 0\n'
                                     'fi\n'
                                     '\n'
                                     'echo "Update/install required:"\n'
                                     'echo "$UPDATE_REASON"\n'
                                     'echo\n'
                                     '\n'
                                     'echo "[3/5] Downloading latest Linux AppImage..."\n'
                                     '\n'
                                     'if command -v curl >/dev/null 2>&1; then\n'
                                     '    curl -L --fail --user-agent "$USER_AGENT" "$DOWNLOAD_URL" -o '
                                     '"$DOWNLOAD_FILE"\n'
                                     'elif command -v wget >/dev/null 2>&1; then\n'
                                     '    wget --user-agent="$USER_AGENT" -O "$DOWNLOAD_FILE" "$DOWNLOAD_URL"\n'
                                     'else\n'
                                     '    echo "[ERROR] curl or wget is required to download the AppImage."\n'
                                     '    exit 1\n'
                                     'fi\n'
                                     '\n'
                                     'if [[ ! -s "$DOWNLOAD_FILE" ]]; then\n'
                                     '    echo "[ERROR] Download failed or downloaded file is empty."\n'
                                     '    exit 1\n'
                                     'fi\n'
                                     '\n'
                                     'echo "Download complete."\n'
                                     'echo\n'
                                     '\n'
                                     'echo "[4/5] Installing AppImage to USB root..."\n'
                                     '\n'
                                     'mkdir -p "$DATA_DIR"\n'
                                     'cp "$DOWNLOAD_FILE" "$APPIMAGE_PATH"\n'
                                     'chmod +x "$APPIMAGE_PATH"\n'
                                     '\n'
                                     'ln -sfn "OpenRCT2.AppImage" "$SYMLINK_PATH" 2>/dev/null || true\n'
                                     '\n'
                                     'echo "[5/5] Writing version marker..."\n'
                                     '\n'
                                     'printf "%s\\n" "$LATEST_VERSION" > "$UPDATED_FILE"\n'
                                     '\n'
                                     'echo\n'
                                     'echo "===================================================="\n'
                                     'echo " Update Complete!"\n'
                                     'echo " OpenRCT2 Linux AppImage is now updated to: $LATEST_VERSION"\n'
                                     'echo "===================================================="\n'
                                     'echo\n'
                                     'echo "Run it with:"\n'
                                     'echo "  \\"$APPIMAGE_PATH\\" --user-data-path=\\"$DATA_DIR\\""\n',
 'Linux/usb_scanner.sh': '#!/usr/bin/env bash\n'
                         'set -u\n'
                         '\n'
                         'USB_PATH=""\n'
                         '\n'
                         'for path in /media/*/OpenRCT2_USB /run/media/*/OpenRCT2_USB /mnt/OpenRCT2_USB; do\n'
                         '    if [ -d "$path" ]; then\n'
                         '        USB_PATH="$path"\n'
                         '        break\n'
                         '    fi\n'
                         'done\n'
                         '\n'
                         'if [ -z "$USB_PATH" ]; then\n'
                         '    echo "Error: USB drive labeled OpenRCT2_USB was not found."\n'
                         '    exit 1\n'
                         'fi\n'
                         '\n'
                         'mkdir -p "$USB_PATH/data"\n'
                         '\n'
                         'if [ -f "$USB_PATH/OpenRCT2.AppImage" ]; then\n'
                         '    chmod +x "$USB_PATH/OpenRCT2.AppImage"\n'
                         '    "$USB_PATH/OpenRCT2.AppImage" --user-data-path="$USB_PATH/data" >/dev/null 2>&1 &\n'
                         '    exit 0\n'
                         'fi\n'
                         '\n'
                         'if [ -f "$USB_PATH/openrct2" ]; then\n'
                         '    chmod +x "$USB_PATH/openrct2"\n'
                         '    "$USB_PATH/openrct2" --user-data-path="$USB_PATH/data" >/dev/null 2>&1 &\n'
                         '    exit 0\n'
                         'fi\n'
                         '\n'
                         'echo "Error: OpenRCT2 executable was not found."\n'
                         'exit 1\n',
 'README.txt': 'OPENRCT2 USB PORTABLE SUITE\n'
               '\n'
               'Recommended USB label:\n'
               'OpenRCT2_USB\n'
               'or:\n'
               'OpenRCT2 USB\n'
               '\n'
               'Recommended USB layout after install:\n'
               'USB_ROOT/\n'
               '  data/\n'
               '  logs/\n'
               '  updated.txt\n'
               '  updated-linux.txt\n'
               '  updated-macos.txt\n'
               '  openrct2.exe                 Windows portable executable after install/update\n'
               '  OpenRCT2.AppImage            Linux executable after install/update\n'
               '  OpenRCT2.app                 macOS app after install/update\n'
               '  Windows/\n'
               '  Linux/\n'
               '  macOS/\n'
               '\n'
               'Best start:\n'
               '1. Put this whole suite on your USB drive.\n'
               '2. Rename the USB drive label to:\n'
               '   OpenRCT2_USB\n'
               '3. Run the installer/updater for your OS:\n'
               '   Windows/[INSTALLl - UPDATE] OpenRCT2.bat\n'
               '   Linux/install_update_openrct2.sh\n'
               '   macOS/install_update_openrct2.sh\n'
               '\n'
               'The Windows VBS launcher now:\n'
               '- Finds the USB dynamically.\n'
               '- Accepts OpenRCT2_USB or OpenRCT2 USB as label.\n'
               '- Falls back to searching ready drives for openrct2.exe.\n'
               '- Writes logs/latest.log.\n'
               '- Archives old latest.log files to logs/archive/.\n'
               '- Writes a fallback temp log if the USB is not found.\n',
 'Windows/SETUP_INSTRUCTIONS.txt': 'WINDOWS SETUP\n'
                                   '\n'
                                   'Files:\n'
                                   '- [INSTALLl - UPDATE] OpenRCT2.bat\n'
                                   '- usb_scanner.vbs\n'
                                   '- event_filter.xml\n'
                                   '\n'
                                   'Manual install/update:\n'
                                   'Double-click:\n'
                                   '[INSTALLl - UPDATE] OpenRCT2.bat\n'
                                   '\n'
                                   'It can be placed either in:\n'
                                   '- USB_ROOT/\n'
                                   '- USB_ROOT/Windows/\n'
                                   '\n'
                                   'Automatic launch:\n'
                                   'Use Task Scheduler with usb_scanner.vbs.\n'
                                   '\n'
                                   'Task Scheduler:\n'
                                   '1. Open Task Scheduler.\n'
                                   '2. Create Task.\n'
                                   '3. Trigger: On an event.\n'
                                   '4. Custom event filter.\n'
                                   '5. XML tab.\n'
                                   '6. Paste event_filter.xml.\n'
                                   '7. Action:\n'
                                   '   Choose Startup program\n'
                                   '   Pick the VBS file: "X:\\Windows\\user\\YOURUSERNAME\\usb_scanner.vbs"\n'
                                   '\n'
                                   'X: Gets repalced with your actual USB or script location automaticly when the USB enter and enables.\n'
                                   '\n'
                                   'Logs:\n'
                                   'The VBS writes:\n'
                                   'USB_ROOT\\logs\\latest.log\n'
                                   '\n'
                                   'Old latest.log files are archived to:\n'
                                   'USB_ROOT\\logs\\archive\\\n',
 'Windows/[INSTALLl - UPDATE] OpenRCT2.bat': '@echo off\n'
                                            'setlocal EnableExtensions EnableDelayedExpansion\n'
                                            '\n'
                                            ':: ============================================================\n'
                                            ':: OpenRCT2 Portable Auto-Installer / Auto-Updater for Windows\n'
                                            ':: ============================================================\n'
                                            ':: Put this BAT file in the USB root folder or run it from:\n'
                                            ':: Windows\\[INSTALLl - UPDATE] OpenRCT2.bat\n'
                                            '::\n'
                                            ':: It downloads the latest OpenRCT2 Windows portable x64 ZIP from '
                                            'GitHub.\n'
                                            ':: ============================================================\n'
                                            '\n'
                                            'title OpenRCT2 Portable Auto-Updater\n'
                                            '\n'
                                            'set "SCRIPT_DIR=%~dp0"\n'
                                            'set "USB_ROOT=%SCRIPT_DIR%"\n'
                                            '\n'
                                            'for %%I in ("%SCRIPT_DIR%.") do set "SCRIPT_FOLDER_NAME=%%~nxI"\n'
                                            'if /I "%SCRIPT_FOLDER_NAME%"=="Windows" (\n'
                                            '    for %%I in ("%SCRIPT_DIR%..") do set "USB_ROOT=%%~fI\\"\n'
                                            ')\n'
                                            '\n'
                                            'cd /d "%USB_ROOT%" || (\n'
                                            '    echo [ERROR] Could not switch to USB root:\n'
                                            '    echo %USB_ROOT%\n'
                                            '    pause\n'
                                            '    exit /b 1\n'
                                            ')\n'
                                            '\n'
                                            'set "UPDATED_FILE=%USB_ROOT%updated.txt"\n'
                                            'set "TEMP_DIR=%TEMP%\\OpenRCT2PortableUpdate_%RANDOM%_%RANDOM%"\n'
                                            'set "TEMP_ZIP=%TEMP_DIR%\\openrct2_latest_windows_portable_x64.zip"\n'
                                            'set "RELEASE_INFO_FILE=%TEMP_DIR%\\release_info.txt"\n'
                                            'set "USER_AGENT=Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                                            'OpenRCT2PortableUpdater/1.0"\n'
                                            '\n'
                                            'set "DOWNLOAD_URL="\n'
                                            'set "LATEST_VERSION="\n'
                                            'set "CURRENT_VERSION="\n'
                                            'set "NEEDS_UPDATE=0"\n'
                                            'set "UPDATE_REASON="\n'
                                            '\n'
                                            'echo ====================================================\n'
                                            'echo             OpenRCT2 Portable Auto-Updater\n'
                                            'echo ====================================================\n'
                                            'echo Target Directory: %USB_ROOT%\n'
                                            'echo.\n'
                                            '\n'
                                            'mkdir "%TEMP_DIR%" >nul 2>&1\n'
                                            '\n'
                                            'echo [1/5] Checking latest OpenRCT2 release from GitHub...\n'
                                            '\n'
                                            'powershell -NoProfile -ExecutionPolicy Bypass -Command ^\n'
                                            '    "$ErrorActionPreference = \'Stop\';" ^\n'
                                            '    "[Net.ServicePointManager]::SecurityProtocol = '
                                            '[Net.SecurityProtocolType]::Tls12;" ^\n'
                                            '    "$headers = @{ \'User-Agent\' = \'%USER_AGENT%\' };" ^\n'
                                            '    "$release = Invoke-RestMethod -Uri '
                                            "'https://api.github.com/repos/OpenRCT2/OpenRCT2/releases/latest' -Headers "
                                            '$headers;" ^\n'
                                            '    "$asset = $release.assets | Where-Object { $_.name -match '
                                            '\'windows-portable-x64\\.zip$\' } | Select-Object -First 1;" ^\n'
                                            '    "if (-not $asset) { throw \'Could not find a windows-portable-x64.zip '
                                            'release asset.\' }" ^\n'
                                            '    "$lines = @($release.tag_name, $asset.browser_download_url, '
                                            '$asset.name);" ^\n'
                                            '    "Set-Content -LiteralPath \'%RELEASE_INFO_FILE%\' -Value $lines '
                                            '-Encoding ASCII;"\n'
                                            '\n'
                                            'if errorlevel 1 goto GITHUB_ERROR\n'
                                            'if not exist "%RELEASE_INFO_FILE%" goto GITHUB_ERROR\n'
                                            '\n'
                                            'set /a LINE_NUM=0\n'
                                            'for /f "usebackq delims=" %%A in ("%RELEASE_INFO_FILE%") do (\n'
                                            '    set /a LINE_NUM+=1\n'
                                            '    if !LINE_NUM! EQU 1 set "LATEST_VERSION=%%A"\n'
                                            '    if !LINE_NUM! EQU 2 set "DOWNLOAD_URL=%%A"\n'
                                            '    if !LINE_NUM! EQU 3 set "ASSET_NAME=%%A"\n'
                                            ')\n'
                                            '\n'
                                            'if "%LATEST_VERSION%"=="" goto GITHUB_ERROR\n'
                                            'if "%DOWNLOAD_URL%"=="" goto GITHUB_ERROR\n'
                                            '\n'
                                            'echo Latest version: %LATEST_VERSION%\n'
                                            'echo Asset: %ASSET_NAME%\n'
                                            'echo.\n'
                                            '\n'
                                            'echo [2/5] Checking local installation...\n'
                                            '\n'
                                            'if not exist "%USB_ROOT%openrct2.exe" (\n'
                                            '    set "NEEDS_UPDATE=1"\n'
                                            '    set "UPDATE_REASON=openrct2.exe is missing."\n'
                                            '    goto CHECK_DONE\n'
                                            ')\n'
                                            '\n'
                                            'if not exist "%UPDATED_FILE%" (\n'
                                            '    set "NEEDS_UPDATE=1"\n'
                                            '    set "UPDATE_REASON=updated.txt is missing."\n'
                                            '    goto CHECK_DONE\n'
                                            ')\n'
                                            '\n'
                                            'set /p CURRENT_VERSION=<"%UPDATED_FILE%"\n'
                                            '\n'
                                            'if "%CURRENT_VERSION%"=="" (\n'
                                            '    set "NEEDS_UPDATE=1"\n'
                                            '    set "UPDATE_REASON=updated.txt is empty."\n'
                                            '    goto CHECK_DONE\n'
                                            ')\n'
                                            '\n'
                                            'if /I not "%CURRENT_VERSION%"=="%LATEST_VERSION%" (\n'
                                            '    set "NEEDS_UPDATE=1"\n'
                                            '    set "UPDATE_REASON=Installed version \'%CURRENT_VERSION%\' does not '
                                            'match latest \'%LATEST_VERSION%\'."\n'
                                            '    goto CHECK_DONE\n'
                                            ')\n'
                                            '\n'
                                            ':CHECK_DONE\n'
                                            '\n'
                                            'if "%NEEDS_UPDATE%"=="0" (\n'
                                            '    echo Current version: %CURRENT_VERSION%\n'
                                            '    echo Latest version:  %LATEST_VERSION%\n'
                                            '    echo.\n'
                                            '    echo ====================================================\n'
                                            '    echo  No new updates were found.\n'
                                            '    echo ====================================================\n'
                                            '    echo.\n'
                                            '    call :CLEANUP\n'
                                            '    pause\n'
                                            '    exit /b 0\n'
                                            ')\n'
                                            '\n'
                                            'echo Update/install required:\n'
                                            'echo %UPDATE_REASON%\n'
                                            'echo.\n'
                                            '\n'
                                            'echo [3/5] Downloading latest Windows portable ZIP...\n'
                                            '\n'
                                            'powershell -NoProfile -ExecutionPolicy Bypass -Command ^\n'
                                            '    "$ErrorActionPreference = \'Stop\';" ^\n'
                                            '    "[Net.ServicePointManager]::SecurityProtocol = '
                                            '[Net.SecurityProtocolType]::Tls12;" ^\n'
                                            '    "$ProgressPreference = \'Continue\';" ^\n'
                                            '    "$headers = @{ \'User-Agent\' = \'%USER_AGENT%\' };" ^\n'
                                            '    "Invoke-WebRequest -Uri \'%DOWNLOAD_URL%\' -OutFile \'%TEMP_ZIP%\' '
                                            '-Headers $headers;"\n'
                                            '\n'
                                            'if errorlevel 1 (\n'
                                            '    echo.\n'
                                            '    echo [ERROR] Download failed.\n'
                                            '    call :CLEANUP\n'
                                            '    pause\n'
                                            '    exit /b 1\n'
                                            ')\n'
                                            '\n'
                                            'if not exist "%TEMP_ZIP%" (\n'
                                            '    echo.\n'
                                            '    echo [ERROR] Download failed. ZIP file was not created.\n'
                                            '    call :CLEANUP\n'
                                            '    pause\n'
                                            '    exit /b 1\n'
                                            ')\n'
                                            '\n'
                                            'echo Download complete.\n'
                                            'echo.\n'
                                            '\n'
                                            'echo [4/5] Extracting files to USB root...\n'
                                            '\n'
                                            'powershell -NoProfile -ExecutionPolicy Bypass -Command ^\n'
                                            '    "$ErrorActionPreference = \'Stop\';" ^\n'
                                            '    "Expand-Archive -LiteralPath \'%TEMP_ZIP%\' -DestinationPath '
                                            '\'%USB_ROOT%\' -Force;"\n'
                                            '\n'
                                            'if errorlevel 1 (\n'
                                            '    echo.\n'
                                            '    echo [ERROR] Extracting the ZIP failed.\n'
                                            '    call :CLEANUP\n'
                                            '    pause\n'
                                            '    exit /b 1\n'
                                            ')\n'
                                            '\n'
                                            'if not exist "%USB_ROOT%data" mkdir "%USB_ROOT%data" >nul 2>&1\n'
                                            '\n'
                                            'echo [5/5] Writing version marker...\n'
                                            '\n'
                                            '> "%UPDATED_FILE%" echo %LATEST_VERSION%\n'
                                            '\n'
                                            'echo.\n'
                                            'echo ====================================================\n'
                                            'echo  Update Complete!\n'
                                            'echo  OpenRCT2 is now updated to: %LATEST_VERSION%\n'
                                            'echo ====================================================\n'
                                            'echo.\n'
                                            'echo updated.txt has been written with:\n'
                                            'echo %LATEST_VERSION%\n'
                                            'echo.\n'
                                            '\n'
                                            'call :CLEANUP\n'
                                            'pause\n'
                                            'exit /b 0\n'
                                            '\n'
                                            ':GITHUB_ERROR\n'
                                            'echo.\n'
                                            'echo [ERROR] Failed to get latest release information from GitHub.\n'
                                            'echo Make sure this PC has internet access and GitHub is reachable.\n'
                                            'echo.\n'
                                            'call :CLEANUP\n'
                                            'pause\n'
                                            'exit /b 1\n'
                                            '\n'
                                            ':CLEANUP\n'
                                            'if exist "%TEMP_DIR%" rmdir /s /q "%TEMP_DIR%" >nul 2>&1\n'
                                            'exit /b 0\n',
 'Windows/event_filter.xml': '<QueryList>\n'
                             '  <Query Id="0" Path="Microsoft-Windows-Partition/Diagnostic">\n'
                             '    <Select Path="Microsoft-Windows-Partition/Diagnostic">\n'
                             '      *[System[(EventID=1006)]] and *[EventData[Data and (Data != '')]]\n'
                             '    </Select>\n'
                             '  </Query>\n'
                             '</QueryList>\n',                             
 'Windows/usb_scanner.vbs': 'Option Explicit\n'
                            '\n'
                            'Dim objShell, objFSO\n'
                            'Dim strUSB, strTargetExe, strDataFolder, strLaunch\n'
                            'Dim strLogDir, strArchiveDir, strLogFile\n'
                            'Dim foundDrive\n'
                            'Dim preLog\n'
                            '\n'
                            'Set objShell = CreateObject("WScript.Shell")\n'
                            'Set objFSO = CreateObject("Scripting.FileSystemObject")\n'
                            '\n'
                            'foundDrive = False\n'
                            'strUSB = ""\n'
                            'preLog = ""\n'
                            '\n'
                            'Call PreLogLine("============================================================")\n'
                            'Call PreLogLine("OpenRCT2 USB launcher started")\n'
                            'Call PreLogLine("Script path: " & WScript.ScriptFullName)\n'
                            '\n'
                            "' ============================================================\n"
                            "' 1. Find the OpenRCT2 USB dynamically\n"
                            "'    This does NOT assume E:\\ or any fixed drive letter.\n"
                            "' ============================================================\n"
                            '\n'
                            'Call FindUsbDrive()\n'
                            '\n'
                            'If foundDrive = False Then\n'
                            '    Call WriteFallbackTempLog()\n'
                            '    WScript.Quit 1\n'
                            'End If\n'
                            '\n'
                            "' ============================================================\n"
                            "' 2. Prepare log folders on the detected USB drive\n"
                            "'    Example result:\n"
                            "'    D:\\logs\\latest.log\n"
                            "'    E:\\logs\\latest.log\n"
                            "'    F:\\logs\\latest.log\n"
                            "'    depending on what Windows assigns.\n"
                            "' ============================================================\n"
                            '\n'
                            'strLogDir = strUSB & "logs"\n'
                            'strArchiveDir = strLogDir & "\\archive"\n'
                            'strLogFile = strLogDir & "\\latest.log"\n'
                            '\n'
                            'Call EnsureFolder(strLogDir)\n'
                            'Call EnsureFolder(strArchiveDir)\n'
                            '\n'
                            'Call ArchiveOldLatestLog()\n'
                            '\n'
                            'Call FlushPreLog()\n'
                            '\n'
                            'Call LogLine("Detected USB root: " & strUSB)\n'
                            'Call LogLine("Log file: " & strLogFile)\n'
                            '\n'
                            "' ============================================================\n"
                            "' 3. Prepare OpenRCT2 paths on the detected USB drive\n"
                            "' ============================================================\n"
                            '\n'
                            'strTargetExe = strUSB & "openrct2.exe"\n'
                            'strDataFolder = strUSB & "data"\n'
                            '\n'
                            'Call LogLine("Target exe: " & strTargetExe)\n'
                            'Call LogLine("Data folder: " & strDataFolder)\n'
                            '\n'
                            'If objFSO.FileExists(strTargetExe) = False Then\n'
                            '    Call LogLine("ERROR: openrct2.exe does not exist: " & strTargetExe)\n'
                            '    WScript.Quit 2\n'
                            'End If\n'
                            '\n'
                            'If objFSO.FolderExists(strDataFolder) = False Then\n'
                            '    Call LogLine("WARNING: data folder does not exist, creating: " & strDataFolder)\n'
                            '\n'
                            '    On Error Resume Next\n'
                            '    objFSO.CreateFolder(strDataFolder)\n'
                            '\n'
                            '    If Err.Number <> 0 Then\n'
                            '        Call LogLine("ERROR: Could not create data folder: " & Err.Description)\n'
                            '        Err.Clear\n'
                            '        WScript.Quit 3\n'
                            '    End If\n'
                            '\n'
                            '    On Error GoTo 0\n'
                            'End If\n'
                            '\n'
                            "' ============================================================\n"
                            "' 4. Launch OpenRCT2 from the detected USB drive\n"
                            "' ============================================================\n"
                            '\n'
                            'objShell.CurrentDirectory = strUSB\n'
                            '\n'
                            'strLaunch = """" & strTargetExe & """ --user-data-path=""" & strDataFolder & """"\n'
                            '\n'
                            'Call LogLine("Launching command:")\n'
                            'Call LogLine(strLaunch)\n'
                            '\n'
                            'objShell.Run strLaunch, 1, False\n'
                            '\n'
                            'Call LogLine("Launch command sent.")\n'
                            'WScript.Quit 0\n'
                            '\n'
                            '\n'
                            "' ============================================================\n"
                            "' Functions\n"
                            "' ============================================================\n"
                            '\n'
                            'Sub FindUsbDrive()\n'
                            '    Dim objDrive\n'
                            '    Dim strVolumeName\n'
                            '    Dim candidateExe\n'
                            '    Dim candidateData\n'
                            '\n'
                            '    Call PreLogLine("Searching for OpenRCT2 USB dynamically...")\n'
                            '\n'
                            "    ' ------------------------------------------------------------\n"
                            "    ' First search by USB volume label.\n"
                            "    ' This accepts both:\n"
                            "    ' OpenRCT2_USB\n"
                            "    ' OpenRCT2 USB\n"
                            "    ' ------------------------------------------------------------\n"
                            '\n'
                            '    For Each objDrive In objFSO.Drives\n'
                            '        On Error Resume Next\n'
                            '\n'
                            '        If objDrive.IsReady Then\n'
                            '            strVolumeName = objDrive.VolumeName\n'
                            '\n'
                            '            Call PreLogLine("Found ready drive " & objDrive.DriveLetter & ":\\ label=[" & '
                            'strVolumeName & "]")\n'
                            '\n'
                            '            If LCase(strVolumeName) = LCase("OpenRCT2_USB") Or _\n'
                            '               LCase(strVolumeName) = LCase("OpenRCT2 USB") Then\n'
                            '\n'
                            '                strUSB = objDrive.DriveLetter & ":\\"\n'
                            '                foundDrive = True\n'
                            '\n'
                            '                Call PreLogLine("Matched USB by volume label: " & strUSB)\n'
                            '                Exit Sub\n'
                            '            End If\n'
                            '        Else\n'
                            '            Call PreLogLine("Drive " & objDrive.DriveLetter & ":\\ is not ready.")\n'
                            '        End If\n'
                            '\n'
                            '        On Error GoTo 0\n'
                            '    Next\n'
                            '\n'
                            "    ' ------------------------------------------------------------\n"
                            "    ' Fallback search:\n"
                            "    ' If the label is wrong, search every ready drive for:\n"
                            "    ' openrct2.exe\n"
                            "    ' data folder\n"
                            "    '\n"
                            "    ' This still does NOT assume a fixed drive letter.\n"
                            "    ' ------------------------------------------------------------\n"
                            '\n'
                            '    Call PreLogLine("No matching USB label found.")\n'
                            '    Call PreLogLine("Trying fallback search for openrct2.exe and data folder...")\n'
                            '\n'
                            '    For Each objDrive In objFSO.Drives\n'
                            '        On Error Resume Next\n'
                            '\n'
                            '        If objDrive.IsReady Then\n'
                            '            candidateExe = objDrive.DriveLetter & ":\\openrct2.exe"\n'
                            '            candidateData = objDrive.DriveLetter & ":\\data"\n'
                            '\n'
                            '            Call PreLogLine("Checking fallback candidate: " & objDrive.DriveLetter & '
                            '":\\")\n'
                            '\n'
                            '            If objFSO.FileExists(candidateExe) Then\n'
                            '                strUSB = objDrive.DriveLetter & ":\\"\n'
                            '                foundDrive = True\n'
                            '\n'
                            '                Call PreLogLine("Matched USB by openrct2.exe fallback: " & strUSB)\n'
                            '\n'
                            '                If objFSO.FolderExists(candidateData) Then\n'
                            '                    Call PreLogLine("Data folder also exists on fallback drive.")\n'
                            '                Else\n'
                            '                    Call PreLogLine("Data folder does not exist yet on fallback drive. It '
                            'will be created.")\n'
                            '                End If\n'
                            '\n'
                            '                Exit Sub\n'
                            '            End If\n'
                            '        End If\n'
                            '\n'
                            '        On Error GoTo 0\n'
                            '    Next\n'
                            '\n'
                            '    Call PreLogLine("ERROR: No OpenRCT2 USB found on any drive letter.")\n'
                            'End Sub\n'
                            '\n'
                            '\n'
                            'Sub ArchiveOldLatestLog()\n'
                            '    Dim timestamp\n'
                            '    Dim archiveZip\n'
                            '    Dim backupLog\n'
                            '    Dim psCommand\n'
                            '    Dim quotedLogFile\n'
                            '    Dim quotedArchiveZip\n'
                            '\n'
                            '    If objFSO.FileExists(strLogFile) = False Then\n'
                            '        Call PreLogLine("No existing latest.log found. No archive needed.")\n'
                            '        Exit Sub\n'
                            '    End If\n'
                            '\n'
                            '    timestamp = GetSafeTimestamp()\n'
                            '    archiveZip = strArchiveDir & "\\openrct2_usb_launcher_" & timestamp & ".zip"\n'
                            '    backupLog = strArchiveDir & "\\openrct2_usb_launcher_" & timestamp & ".log.bak"\n'
                            '\n'
                            '    Call PreLogLine("Existing latest.log found.")\n'
                            '    Call PreLogLine("Archiving old latest.log to: " & archiveZip)\n'
                            '\n'
                            '    quotedLogFile = Replace(strLogFile, "\'", "\'\'")\n'
                            '    quotedArchiveZip = Replace(archiveZip, "\'", "\'\'")\n'
                            '\n'
                            '    psCommand = "powershell.exe -NoProfile -ExecutionPolicy Bypass -Command " & _\n'
                            '                """Compress-Archive -LiteralPath \'" & quotedLogFile & "\' " & _\n'
                            '                "-DestinationPath \'" & quotedArchiveZip & "\' -Force"""\n'
                            '\n'
                            '    On Error Resume Next\n'
                            '    objShell.Run psCommand, 0, True\n'
                            '\n'
                            '    If Err.Number <> 0 Then\n'
                            '        Call PreLogLine("WARNING: PowerShell Compress-Archive failed: " & '
                            'Err.Description)\n'
                            '        Err.Clear\n'
                            '    End If\n'
                            '\n'
                            '    On Error GoTo 0\n'
                            '\n'
                            '    If objFSO.FileExists(archiveZip) Then\n'
                            '        On Error Resume Next\n'
                            '        objFSO.DeleteFile strLogFile, True\n'
                            '\n'
                            '        If Err.Number <> 0 Then\n'
                            '            Call PreLogLine("WARNING: Zip was created but old latest.log could not be '
                            'deleted: " & Err.Description)\n'
                            '            Err.Clear\n'
                            '        Else\n'
                            '            Call PreLogLine("Old latest.log zipped and removed successfully.")\n'
                            '        End If\n'
                            '\n'
                            '        On Error GoTo 0\n'
                            '    Else\n'
                            '        Call PreLogLine("WARNING: Zip archive was not created.")\n'
                            '        Call PreLogLine("Trying fallback backup move to: " & backupLog)\n'
                            '\n'
                            '        On Error Resume Next\n'
                            '        objFSO.MoveFile strLogFile, backupLog\n'
                            '\n'
                            '        If Err.Number <> 0 Then\n'
                            '            Call PreLogLine("ERROR: Could not move old latest.log to backup: " & '
                            'Err.Description)\n'
                            '            Err.Clear\n'
                            '        Else\n'
                            '            Call PreLogLine("Old latest.log moved to .log.bak fallback successfully.")\n'
                            '        End If\n'
                            '\n'
                            '        On Error GoTo 0\n'
                            '    End If\n'
                            'End Sub\n'
                            '\n'
                            '\n'
                            'Sub EnsureFolder(ByVal folderPath)\n'
                            '    Dim parentPath\n'
                            '\n'
                            '    If objFSO.FolderExists(folderPath) Then\n'
                            '        Exit Sub\n'
                            '    End If\n'
                            '\n'
                            '    parentPath = objFSO.GetParentFolderName(folderPath)\n'
                            '\n'
                            '    If parentPath <> "" Then\n'
                            '        If objFSO.FolderExists(parentPath) = False Then\n'
                            '            Call EnsureFolder(parentPath)\n'
                            '        End If\n'
                            '    End If\n'
                            '\n'
                            '    On Error Resume Next\n'
                            '    objFSO.CreateFolder(folderPath)\n'
                            '\n'
                            '    If Err.Number <> 0 Then\n'
                            '        Call PreLogLine("ERROR: Could not create folder: " & folderPath & " - " & '
                            'Err.Description)\n'
                            '        Err.Clear\n'
                            '    Else\n'
                            '        Call PreLogLine("Created folder: " & folderPath)\n'
                            '    End If\n'
                            '\n'
                            '    On Error GoTo 0\n'
                            'End Sub\n'
                            '\n'
                            '\n'
                            'Sub PreLogLine(ByVal msg)\n'
                            '    preLog = preLog & Now & " - " & msg & vbCrLf\n'
                            'End Sub\n'
                            '\n'
                            '\n'
                            'Sub FlushPreLog()\n'
                            '    Dim logFile\n'
                            '\n'
                            '    On Error Resume Next\n'
                            '\n'
                            '    Set logFile = objFSO.OpenTextFile(strLogFile, 8, True)\n'
                            '    logFile.Write preLog\n'
                            '    logFile.Close\n'
                            '\n'
                            '    If Err.Number <> 0 Then\n'
                            '        Err.Clear\n'
                            '    End If\n'
                            '\n'
                            '    On Error GoTo 0\n'
                            'End Sub\n'
                            '\n'
                            '\n'
                            'Sub LogLine(ByVal msg)\n'
                            '    Dim logFile\n'
                            '\n'
                            '    On Error Resume Next\n'
                            '\n'
                            '    Set logFile = objFSO.OpenTextFile(strLogFile, 8, True)\n'
                            '    logFile.WriteLine Now & " - " & msg\n'
                            '    logFile.Close\n'
                            '\n'
                            '    If Err.Number <> 0 Then\n'
                            '        Err.Clear\n'
                            '    End If\n'
                            '\n'
                            '    On Error GoTo 0\n'
                            'End Sub\n'
                            '\n'
                            '\n'
                            'Sub WriteFallbackTempLog()\n'
                            '    Dim tempLogFile\n'
                            '    Dim logFile\n'
                            '\n'
                            '    tempLogFile = '
                            'objShell.ExpandEnvironmentStrings("%TEMP%\\openrct2_usb_launcher_fallback.log")\n'
                            '\n'
                            '    On Error Resume Next\n'
                            '\n'
                            '    Set logFile = objFSO.OpenTextFile(tempLogFile, 8, True)\n'
                            '    logFile.Write preLog\n'
                            '    logFile.WriteLine Now & " - USB was not found, so USB logs\\latest.log could not be '
                            'created."\n'
                            '    logFile.WriteLine Now & " - This fallback log is only used when no matching USB is '
                            'detected."\n'
                            '    logFile.Close\n'
                            '\n'
                            '    On Error GoTo 0\n'
                            'End Sub\n'
                            '\n'
                            '\n'
                            'Function GetSafeTimestamp()\n'
                            '    Dim d\n'
                            '\n'
                            '    d = Now\n'
                            '\n'
                            '    GetSafeTimestamp = _\n'
                            '        Year(d) & "-" & _\n'
                            '        Right("0" & Month(d), 2) & "-" & _\n'
                            '        Right("0" & Day(d), 2) & "_" & _\n'
                            '        Right("0" & Hour(d), 2) & "-" & _\n'
                            '        Right("0" & Minute(d), 2) & "-" & _\n'
                            '        Right("0" & Second(d), 2)\n'
                            'End Function\n',
 'macOS/SETUP_INSTRUCTIONS.txt': 'macOS SETUP\n'
                                 '\n'
                                 'Files:\n'
                                 '- install_update_openrct2.sh\n'
                                 '- usb_scanner.sh\n'
                                 '- com.goi.usbscanner.plist\n'
                                 '\n'
                                 'Manual install/update:\n'
                                 '1. Open Terminal in the USB folder.\n'
                                 '2. Run:\n'
                                 '   chmod +x macOS/install_update_openrct2.sh\n'
                                 '   ./macOS/install_update_openrct2.sh\n'
                                 '\n'
                                 'The updater downloads:\n'
                                 'OpenRCT2-v*-macos-universal.zip\n'
                                 '\n'
                                 'Automatic launch:\n'
                                 '1. Copy macOS/usb_scanner.sh to:\n'
                                 '   /usr/local/bin/usb_scanner.sh\n'
                                 '\n'
                                 '2. Make it executable:\n'
                                 '   chmod +x /usr/local/bin/usb_scanner.sh\n'
                                 '\n'
                                 '3. Copy macOS/com.goi.usbscanner.plist to:\n'
                                 '   ~/Library/LaunchAgents/com.goi.usbscanner.plist\n'
                                 '\n'
                                 '4. Load:\n'
                                 '   launchctl load ~/Library/LaunchAgents/com.goi.usbscanner.plist\n'
                                 '\n'
                                 'macOS may still ask security permission before opening downloaded apps.\n',
 'macOS/com.goi.usbscanner.plist': '<?xml version="1.0" encoding="UTF-8"?>\n'
                                   '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"\n'
                                   ' "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
                                   '<plist version="1.0">\n'
                                   '  <dict>\n'
                                   '    <key>Label</key>\n'
                                   '    <string>com.goi.usbscanner</string>\n'
                                   '\n'
                                   '    <key>ProgramArguments</key>\n'
                                   '    <array>\n'
                                   '      <string>/usr/local/bin/usb_scanner.sh</string>\n'
                                   '    </array>\n'
                                   '\n'
                                   '    <key>StartInterval</key>\n'
                                   '    <integer>10</integer>\n'
                                   '\n'
                                   '    <key>RunAtLoad</key>\n'
                                   '    <true/>\n'
                                   '\n'
                                   '    <key>StandardOutPath</key>\n'
                                   '    <string>/tmp/com.goi.usbscanner.out.log</string>\n'
                                   '\n'
                                   '    <key>StandardErrorPath</key>\n'
                                   '    <string>/tmp/com.goi.usbscanner.err.log</string>\n'
                                   '  </dict>\n'
                                   '</plist>\n',
 'macOS/install_update_openrct2.sh': '#!/usr/bin/env bash\n'
                                     'set -Eeuo pipefail\n'
                                     '\n'
                                     'SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"\n'
                                     'USB_ROOT="$SCRIPT_DIR"\n'
                                     '\n'
                                     'if [[ "$(basename "$SCRIPT_DIR")" == "macOS" ]]; then\n'
                                     '    USB_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"\n'
                                     'fi\n'
                                     '\n'
                                     'UPDATED_FILE="$USB_ROOT/updated-macos.txt"\n'
                                     'APP_PATH="$USB_ROOT/OpenRCT2.app"\n'
                                     'DATA_DIR="$USB_ROOT/data"\n'
                                     'TEMP_DIR="$(mktemp -d)"\n'
                                     'RELEASE_INFO_FILE="$TEMP_DIR/release_info.txt"\n'
                                     'DOWNLOAD_ZIP="$TEMP_DIR/OpenRCT2-macos-universal.zip"\n'
                                     'EXTRACT_DIR="$TEMP_DIR/extracted"\n'
                                     'USER_AGENT="OpenRCT2PortableUpdater/1.0"\n'
                                     '\n'
                                     'cleanup() {\n'
                                     '    rm -rf "$TEMP_DIR"\n'
                                     '}\n'
                                     'trap cleanup EXIT\n'
                                     '\n'
                                     'echo "===================================================="\n'
                                     'echo "        OpenRCT2 Portable Auto-Updater - macOS"\n'
                                     'echo "===================================================="\n'
                                     'echo "Target directory: $USB_ROOT"\n'
                                     'echo\n'
                                     '\n'
                                     'echo "[1/5] Checking latest OpenRCT2 release from GitHub..."\n'
                                     '\n'
                                     'if ! command -v python3 >/dev/null 2>&1; then\n'
                                     '    echo "[ERROR] python3 is required for parsing the GitHub release JSON."\n'
                                     '    exit 1\n'
                                     'fi\n'
                                     '\n'
                                     'python3 - "$RELEASE_INFO_FILE" <<\'PY\'\n'
                                     'import json\n'
                                     'import sys\n'
                                     'import urllib.request\n'
                                     '\n'
                                     'output_file = sys.argv[1]\n'
                                     'url = "https://api.github.com/repos/OpenRCT2/OpenRCT2/releases/latest"\n'
                                     'request = urllib.request.Request(url, headers={"User-Agent": '
                                     '"OpenRCT2PortableUpdater/1.0"})\n'
                                     '\n'
                                     'with urllib.request.urlopen(request, timeout=60) as response:\n'
                                     '    release = json.loads(response.read().decode("utf-8"))\n'
                                     '\n'
                                     'tag = release.get("tag_name", "")\n'
                                     'asset = None\n'
                                     '\n'
                                     'for item in release.get("assets", []):\n'
                                     '    name = item.get("name", "")\n'
                                     '    if name.endswith("macos-universal.zip"):\n'
                                     '        asset = item\n'
                                     '        break\n'
                                     '\n'
                                     'if not tag or not asset:\n'
                                     '    raise SystemExit("Could not find latest macos-universal.zip asset.")\n'
                                     '\n'
                                     'with open(output_file, "w", encoding="utf-8") as f:\n'
                                     '    f.write(tag + "\\n")\n'
                                     '    f.write(asset["browser_download_url"] + "\\n")\n'
                                     '    f.write(asset["name"] + "\\n")\n'
                                     'PY\n'
                                     '\n'
                                     'LATEST_VERSION="$(sed -n \'1p\' "$RELEASE_INFO_FILE")"\n'
                                     'DOWNLOAD_URL="$(sed -n \'2p\' "$RELEASE_INFO_FILE")"\n'
                                     'ASSET_NAME="$(sed -n \'3p\' "$RELEASE_INFO_FILE")"\n'
                                     '\n'
                                     'if [[ -z "$LATEST_VERSION" || -z "$DOWNLOAD_URL" ]]; then\n'
                                     '    echo "[ERROR] Could not read GitHub release information."\n'
                                     '    exit 1\n'
                                     'fi\n'
                                     '\n'
                                     'echo "Latest version: $LATEST_VERSION"\n'
                                     'echo "Asset: $ASSET_NAME"\n'
                                     'echo\n'
                                     '\n'
                                     'echo "[2/5] Checking local installation..."\n'
                                     '\n'
                                     'NEEDS_UPDATE=0\n'
                                     'UPDATE_REASON=""\n'
                                     '\n'
                                     'if [[ ! -d "$APP_PATH" ]]; then\n'
                                     '    NEEDS_UPDATE=1\n'
                                     '    UPDATE_REASON="OpenRCT2.app is missing."\n'
                                     'elif [[ ! -f "$UPDATED_FILE" ]]; then\n'
                                     '    NEEDS_UPDATE=1\n'
                                     '    UPDATE_REASON="updated-macos.txt is missing."\n'
                                     'else\n'
                                     '    CURRENT_VERSION="$(head -n 1 "$UPDATED_FILE" || true)"\n'
                                     '    if [[ -z "$CURRENT_VERSION" ]]; then\n'
                                     '        NEEDS_UPDATE=1\n'
                                     '        UPDATE_REASON="updated-macos.txt is empty."\n'
                                     '    elif [[ "$CURRENT_VERSION" != "$LATEST_VERSION" ]]; then\n'
                                     '        NEEDS_UPDATE=1\n'
                                     '        UPDATE_REASON="Installed version \'$CURRENT_VERSION\' does not match '
                                     'latest \'$LATEST_VERSION\'."\n'
                                     '    fi\n'
                                     'fi\n'
                                     '\n'
                                     'if [[ "$NEEDS_UPDATE" == "0" ]]; then\n'
                                     '    echo "Current version: $(head -n 1 "$UPDATED_FILE")"\n'
                                     '    echo "Latest version:  $LATEST_VERSION"\n'
                                     '    echo\n'
                                     '    echo "===================================================="\n'
                                     '    echo " No new updates were found."\n'
                                     '    echo "===================================================="\n'
                                     '    exit 0\n'
                                     'fi\n'
                                     '\n'
                                     'echo "Update/install required:"\n'
                                     'echo "$UPDATE_REASON"\n'
                                     'echo\n'
                                     '\n'
                                     'echo "[3/5] Downloading latest macOS universal ZIP..."\n'
                                     '\n'
                                     'if command -v curl >/dev/null 2>&1; then\n'
                                     '    curl -L --fail --user-agent "$USER_AGENT" "$DOWNLOAD_URL" -o '
                                     '"$DOWNLOAD_ZIP"\n'
                                     'elif command -v wget >/dev/null 2>&1; then\n'
                                     '    wget --user-agent="$USER_AGENT" -O "$DOWNLOAD_ZIP" "$DOWNLOAD_URL"\n'
                                     'else\n'
                                     '    echo "[ERROR] curl or wget is required to download the ZIP."\n'
                                     '    exit 1\n'
                                     'fi\n'
                                     '\n'
                                     'if [[ ! -s "$DOWNLOAD_ZIP" ]]; then\n'
                                     '    echo "[ERROR] Download failed or downloaded file is empty."\n'
                                     '    exit 1\n'
                                     'fi\n'
                                     '\n'
                                     'echo "Download complete."\n'
                                     'echo\n'
                                     '\n'
                                     'echo "[4/5] Extracting and installing OpenRCT2.app..."\n'
                                     '\n'
                                     'mkdir -p "$EXTRACT_DIR"\n'
                                     'unzip -q "$DOWNLOAD_ZIP" -d "$EXTRACT_DIR"\n'
                                     '\n'
                                     'FOUND_APP="$(find "$EXTRACT_DIR" -maxdepth 3 -name \'OpenRCT2.app\' -type d | '
                                     'head -n 1 || true)"\n'
                                     '\n'
                                     'if [[ -z "$FOUND_APP" ]]; then\n'
                                     '    echo "[ERROR] OpenRCT2.app was not found inside the downloaded ZIP."\n'
                                     '    exit 1\n'
                                     'fi\n'
                                     '\n'
                                     'rm -rf "$APP_PATH"\n'
                                     'cp -R "$FOUND_APP" "$APP_PATH"\n'
                                     'mkdir -p "$DATA_DIR"\n'
                                     '\n'
                                     'echo "[5/5] Writing version marker..."\n'
                                     '\n'
                                     'printf "%s\\n" "$LATEST_VERSION" > "$UPDATED_FILE"\n'
                                     '\n'
                                     'echo\n'
                                     'echo "===================================================="\n'
                                     'echo " Update Complete!"\n'
                                     'echo " OpenRCT2.app is now updated to: $LATEST_VERSION"\n'
                                     'echo "===================================================="\n'
                                     'echo\n'
                                     'echo "Run it with:"\n'
                                     'echo "  open \\"$APP_PATH\\""\n',
 'macOS/usb_scanner.sh': '#!/usr/bin/env bash\n'
                         'set -u\n'
                         '\n'
                         'USB_PATH="/Volumes/OpenRCT2_USB"\n'
                         '\n'
                         'if [ ! -d "$USB_PATH" ]; then\n'
                         '    exit 0\n'
                         'fi\n'
                         '\n'
                         'mkdir -p "$USB_PATH/data"\n'
                         '\n'
                         'if [ -d "$USB_PATH/OpenRCT2.app" ]; then\n'
                         '    open "$USB_PATH/OpenRCT2.app"\n'
                         '    exit 0\n'
                         'fi\n'
                         '\n'
                         'if [ -f "$USB_PATH/openrct2" ]; then\n'
                         '    chmod +x "$USB_PATH/openrct2"\n'
                         '    "$USB_PATH/openrct2" --user-data-path="$USB_PATH/data" >/dev/null 2>&1 &\n'
                         '    exit 0\n'
                         'fi\n'
                         '\n'
                         'echo "Error: OpenRCT2 app/executable was not found."\n'
                         'exit 1\n'}

    def write_package_files(self) -> None:
        """
        Write all setup instructions and helper scripts to the package folder.
        """
        for relative_path, content in self.setup_docs.items():
            output_path = self.package_dir / relative_path
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(content, encoding="utf-8", newline="\n")

    def create_zip(self) -> None:
        """
        Create the final ZIP archive from the package folder.
        """
        zip_path = Path(self.zip_name)

        if zip_path.exists():
            zip_path.unlink()

        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zip_file:
            for file_path in self.package_dir.rglob("*"):
                if file_path.is_file():
                    archive_name = file_path.relative_to(self.package_dir)
                    zip_file.write(file_path, archive_name)

    def run(self) -> None:
        """
        Generate all files and create the ZIP archive.
        """
        self.write_package_files()
        self.create_zip()

        print("Success!")
        print(f"Created folder: {self.package_dir}")
        print(f"Created ZIP: {self.zip_name}")
        print()
        print("Recommended USB labels:")
        print("- OpenRCT2_USB")
        print("- OpenRCT2 USB")


class Main:
    """
    Application entry point class.
    """

    def __init__(self) -> None:
        self.generator = Generator()

    def run(self) -> None:
        self.generator.run()


if __name__ == "__main__":
    app = Main()
    app.run()
